# Generated by Django 4.0 on 2021-12-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('timestamp', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
